language: python
sudo: required
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest

# Run in parallel for each mysql version being tested
env:
  global:
    - CI_NODE_TOTAL=3
  matrix:
  - MONGO_TEST=2.6 CI_NODE_INDEX=0
  - MONGO_TEST=3.0 CI_NODE_INDEX=1
  - MONGO_TEST=3.2 CI_NODE_INDEX=2
  - MYSQL_TEST=5.5 CI_NODE_INDEX=0
  - MYSQL_TEST=5.6 CI_NODE_INDEX=1
  - MYSQL_TEST=5.7 CI_NODE_INDEX=2

# command to build and run tests
script:
  - ssh-keygen -y -f /home/travis/.ssh/id_rsa > /home/travis/.ssh/id_rsa.pub
  - cat /home/travis/.ssh/id_rsa.pub >> /home/travis/.ssh/authorized_keys
  - pytest --capture=no tests
